spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: app
    password: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update        # thay validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true

logging:
  level:
    org.hibernate.SQL: debug
